# Generated by Django 2.1.3 on 2018-11-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('seccion', models.IntegerField()),
                ('año', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipaciónEnCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='RelCursoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Curso')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.Usuario')),
                ('nombre', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
            ],
            bases=('app1.usuario',),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'seccion', 'año')},
        ),
        migrations.AddField(
            model_name='participaciónencurso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.PersonaNatural'),
        ),
        migrations.AlterUniqueTogether(
            name='participaciónencurso',
            unique_together={('persona', 'curso')},
        ),
    ]
