# Generated by Django 2.1.3 on 2018-11-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('Abierta', 'abierta'), ('Cerrada', 'cerrada'), ('Publicada', 'publicada')], default='cerrada', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('seccion', models.IntegerField()),
                ('año', models.IntegerField()),
                ('semestre', models.CharField(choices=[('1', 'otoño'), ('2', 'primavera')], default='otoño', max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionEnCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('profesor', 'profesor'), ('auxiliar', 'auxiliar'), ('ayudante', 'ayudante'), ('alumno', 'alumno')], default='alumno', max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=300)),
                ('ponderacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RelCursoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Curso')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Grupo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'seccion', 'año', 'semestre')},
        ),
        migrations.AddField(
            model_name='coevaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='relcursogrupo',
            unique_together={('grupo', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='participacionencurso',
            unique_together={('persona', 'curso')},
        ),
    ]
