# Generated by Django 2.1.3 on 2018-11-14 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionEnCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('profesor', 'profesor'), ('auxiliar', 'auxiliar'), ('ayudante', 'ayudante'), ('alumno', 'alumno')], default='alumno', max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participaciónencurso',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='participaciónencurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='participaciónencurso',
            name='persona',
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.CharField(choices=[('otoño', 'otoño'), ('primavera', 'primavera')], default='otoño', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='isAdmin',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'seccion', 'año', 'semestre')},
        ),
        migrations.DeleteModel(
            name='ParticipaciónEnCurso',
        ),
        migrations.AddField(
            model_name='participacionencurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Curso'),
        ),
        migrations.AddField(
            model_name='participacionencurso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.PersonaNatural'),
        ),
        migrations.AlterUniqueTogether(
            name='participacionencurso',
            unique_together={('persona', 'curso')},
        ),
    ]
