# Generated by Django 2.1.3 on 2018-11-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181122_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='coevaluacion',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.Curso'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='relcursogrupo',
            unique_together={('grupo', 'curso')},
        ),
    ]
