# Generated by Django 2.1.3 on 2018-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_coevaluacion_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='coevaluacion',
            name='estado',
            field=models.CharField(choices=[('abierta', 'abierta'), ('cerrada', 'cerrada'), ('publicada', 'publicada')], default='cerrada', max_length=9),
        ),
    ]
