# Generated by Django 2.1.3 on 2018-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20181122_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coevaluacion',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'abierta'), ('Cerrada', 'cerrada'), ('Publicada', 'publicada')], default='cerrada', max_length=9),
        ),
    ]
