# Generated by Django 2.1.3 on 2018-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_coevaluacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
