# Generated by Django 2.1.3 on 2018-11-20 22:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_auto_20181120_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personanatural',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='personanatural',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='personanatural',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='personanatural',
            name='usuario_ptr',
        ),
        migrations.AddField(
            model_name='personanatural',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
